### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by almarklein**
* Improve mix, so the mixer value can also be a float if the values-to-mix are vecs.
* Enable using `a % b` and `math.fmod(a, b)`, which both work a bit different. Also test that these work the same as in Python.
* Allow writing `fragDepth`
* Implement unary neg/pos/not.
* Implement inplace add/div/mul/div
* Allow integer division using the `//` operator 
* Implement tuples packing/unpacking (`a,b=c,d`) as syntactic sugar.

### CODE REVIEW

**Comment by Korijn** [comment]
> Also test that these work the same as in Python.

Does that mean some functions work differently than documented in spir-v?

**Comment by almarklein** [comment]
> > Also test that these work the same as in Python.
> 
> Does that mean some functions work differently than documented in spir-v?

The modulo operator has different [flavours](https://en.wikipedia.org/wiki/Modulo_operation), and not all programming languages implement the same one. In Python, with `%` the result takes the sign of the second argument, whereas `math.fmod` takes the sign of the first argument. The latter is also referred to as the "remainder". SpirV supports both. What I meant is that I wrote tests to make sure that using `%` and `math.fmod` both work and produce the same result as in Python :)

**Comment by Korijn** [comment]
Alright, thanks for clarifying. Follow up question: is the default behaviour for `%` in spir-v the same as the Python behaviour for `%`?

**Comment by almarklein** [comment]
>  is the default behaviour for % in spir-v the same as the Python behaviour for %?

SpirV simply has [OpFMod](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpFMod) and [OpFRem](https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpFRem) (and corresponding instructions for integers). There is no default.

**Pull request merged**
